### ISSUE TITLE
Popup text for you tube video titles is broken by this plugin

### ISSUE THREAD

**Issue by deadscreem** [piroor/popupalt#10]
On youtube if you hover over video titles (the text not the thumbnail) it's supposed to popup the full title, useful if the title is very long and got shortened on the page. This is part of youtube's page programming itself. And it seems this plugin is interfering with the page preventing the popups. Disable the plugin and the popups work fine again.

**Comment by piroor** [comment]
Any example URL?

**Comment by deadscreem** [comment]
https://www.youtube.com/ or any where else really. Here is a screen shot showing what should happen. Notice the actual title is shortened with "..." and the popup shows full. This only works when this plugin is disabled. (mouse pointer cant be captured in screenshot so I put a fake one in paint showing where to hover)

![untitled](https://user-images.githubusercontent.com/13713058/51878521-94e84680-2335-11e9-8243-ab5caf8627fe.png)

**Comment by piroor** [comment]
Thanks, the bug has been fixed by 1998c42.
